name: NPM Release

on:
  push:
    tags:
      - v2.*.*

jobs:
  Release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js v12.x
        uses: actions/setup-node@v2
        with:
          node-version: '12.x'
          registry-url: 'https://registry.npmjs.org'
      - name: Install dependencies
        run: npm install
      - name: build package
        run: npm run build
      - name: cp file
        run: cp {package.json,README.md,LICENSE,.npmignore} dist
      - name: Npm publish
        run: npm publish ./dist
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
      
